### PR TITLE
Eucalyptus compatability fixes

### PR DESCRIPTION
**Pull request by bdero**
- Move TOS and about to static_templates directory
- Overrides _variables partial instead of _overrides
- Add symlink for honor code
- Fix banner path
- Remove stanford theme check for youtube video (fixes exception during update_assets)

This theme is live on https://extend.duke.edu/ . To test it, visit the site and poke around. On the registration page, make sure the Terms of Service page shows up when clicking on the Honor Code link.

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
@bdero The username in the top right looks a bit off:
screen shot 2016-09-07 at 2 19 58 pm

Can you please make that text white?

Actually, the whole header has some issues:
screen shot 2016-09-07 at 2 20 45 pm

Note that one "gotcha" with Eucalyptus is that the discussion forum page and all other LMS pages use different layouts. As a result, I'm seeing an "Explore courses" link in the header on that discussion page that isn't on the other pages.

Also, the footer on the discussion pages is broken:
screen shot 2016-09-07 at 2 22 39 pm

**Comment by bdero** [comment]
@bradenmacdonald Thanks for the review. I have some questions/responses below:

> The username in the top right looks a bit off:
> screen shot 2016-09-07 at 2 19 58 pm

Ah, I had the exact same problem with the MITx theme (wrong color, white underline, wrong dropdown button background). I'll address this.

> Actually, the whole header has some issues:
> screen shot 2016-09-07 at 2 20 45 pm

Which browser are you using? In Firefox the user dropdown isn't dipping below the header line. (Either way, I'll try to fix the text and the logo alignment/padding)


> As a result, I'm seeing an "Explore courses" link in the header on that discussion page that isn't on the other pages.

Should I override the discussion page and remove the link, or add the link to the pages which are missing it?

**Comment by bradenmacdonald** [comment]
@bdero Screenshots are from Chrome.

For the "Explore Courses" link, I think it's complicated. In the courseware, the header has the `.slim` class and there is a rule to hide the "global nav" links like "Explore Courses" when the header is in "slim" mode (e.g. when viewing courseware). But the discussion page doesn't have that rule since it uses a different layout/css. Please check what edx.org or a vanilla install does to figure out the correct behavior and fix the CSS bug, whichever way it is.

**Comment by bdero** [comment]
@bradenmacdonald I found that the theme header dipping down is a problem that seems to happen on most edX installations (including courses.edx.org) when the window is a bit too small in any browser.



I fixed it by overriding the width of .course-header to 'auto'

There was quite a bit of trial end error involved, but I think it's good for another review now:

**Comment by bradenmacdonald** [comment]
👍

**Comment by bradenmacdonald** [comment]
@bdero Actually sorry, there are two minor issues:
* Please remove the text shadow from the username. A white shadow behind white text just makes the text harder to read
* The menu dropdown to the right of the username is hard to see - please make it white/light too
screen shot 2016-09-08 at 2 51 45 pm

**Comment by chrislorch** [comment]
One additional issue users noted today- color contrast problem with the
"Explore Courses" header item.[image: Explore_Courses_contrast.jpg]

**Comment by bdero** [comment]
I think I fixed the remaining issues:


It's not live on https://extend.duke.edu yet. I'll be deploying it in a minute.

**Comment by bdero** [comment]
@bradenmacdonald This is ready for review again - the new fixes are live on https://extend.duke.edu/ with eucalyptus.2 now:

I also addressed the weird coloring of the header links that @chrislorch mentioned.

**Comment by bradenmacdonald** [comment]
@bdero Sorry, two minor issues left on the discussion forum page:
* The user account down arrow (same thing I mentioned earlier) is not white on that page
* The footer content should have the same width as the content above (see any non-discussion page), but on the discussion page, the footer content is as wide as the browser window.

Correct:
screen shot 2016-09-09 at 2 46 10 pm

Incorrect:
screen shot 2016-09-09 at 2 46 15 pm

**Comment by bdero** [comment]
@bradenmacdonald Alright, this is live and ready for another round: https://extend.duke.edu/courses/course-v1:DukeExtend+3DP101+2015-16/discussion/forum

**Comment by bradenmacdonald** [comment]
:+1:

- [x] I tested this: On the live site
- [x] I read through the code
- ~~Includes documentation~~: n/a

**Pull request merged**
