### PR TITLE
About updates

### PR DESCRIPTION
**Pull request by hrvalli**
@bradenmacdonald, we've revised the language on our About page for Duke Extend. Please update in your next sprint. If you have any questions, please contact me at heather.valli@duke.edu. Thank you!

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
@hrvalli Sure, and thanks for submitting this as a PR! We'll schedule a quick review next week then merge this and update your site. You'll get the "allow hiding discussion tabs" change at the same time.

**Comment by hrvalli** [comment]
Thank you, Braden! Quick question—how will the "allow hiding discussion tabs" thing work in practice? Is it something where we set "true" or "false" in the advanced settings?

**Comment by bradenmacdonald** [comment]
@hrvalli In Studio, from the Content -> Pages tab for each course, you'll get a new "eye" icon that lets you enable or disable the tab for that course, just like the other tabs:

screen shot 2017-06-02 at 11 46 02 am

**Comment by hrvalli** [comment]
Very intuitive. Thanks!

**Comment by smarnach** [comment]
@profmikegreene @hrvalli I've deployed this change to the staging instance: https://stage.extend.duke.edu/about

Could you please take a quick look?  If everything looks good to you, I'll go ahead and deploy to production.

**Comment by hrvalli** [comment]
Hi Sven. It looks good on our end. Please deploy it to production. 

Have a nice weekend!

**Comment by smarnach** [comment]
@hrvalli Thanks for the quick reply!

**Comment by smarnach** [comment]
@hrvalli @profmikegreene The change has now been deployed to production.

**Pull request merged**
